// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createProjectStmt, err = db.PrepareContext(ctx, createProject); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProject: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteProjectStmt, err = db.PrepareContext(ctx, deleteProject); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProject: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionFilesStmt, err = db.PrepareContext(ctx, deleteSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionFiles: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathAndSessionStmt, err = db.PrepareContext(ctx, getFileByPathAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPathAndSession: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getProjectByIDStmt, err = db.PrepareContext(ctx, getProjectByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProjectByID: %w", err)
	}
	if q.getProjectSessionsStmt, err = db.PrepareContext(ctx, getProjectSessions); err != nil {
		return nil, fmt.Errorf("error preparing query GetProjectSessions: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.listFilesByPathStmt, err = db.PrepareContext(ctx, listFilesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesByPath: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listLatestSessionFilesStmt, err = db.PrepareContext(ctx, listLatestSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionFiles: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listNewFilesStmt, err = db.PrepareContext(ctx, listNewFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListNewFiles: %w", err)
	}
	if q.listProjectsByUserStmt, err = db.PrepareContext(ctx, listProjectsByUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListProjectsByUser: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateProjectStmt, err = db.PrepareContext(ctx, updateProject); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProject: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	if q.createToolCallStmt, err = db.PrepareContext(ctx, createToolCall); err != nil {
		return nil, fmt.Errorf("error preparing query CreateToolCall: %w", err)
	}
	if q.getToolCallStmt, err = db.PrepareContext(ctx, getToolCall); err != nil {
		return nil, fmt.Errorf("error preparing query GetToolCall: %w", err)
	}
	if q.listToolCallsBySessionStmt, err = db.PrepareContext(ctx, listToolCallsBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListToolCallsBySession: %w", err)
	}
	if q.listToolCallsByMessageStmt, err = db.PrepareContext(ctx, listToolCallsByMessage); err != nil {
		return nil, fmt.Errorf("error preparing query ListToolCallsByMessage: %w", err)
	}
	if q.listPendingToolCallsStmt, err = db.PrepareContext(ctx, listPendingToolCalls); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingToolCalls: %w", err)
	}
	if q.updateToolCallStatusStmt, err = db.PrepareContext(ctx, updateToolCallStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateToolCallStatus: %w", err)
	}
	if q.updateToolCallInputStmt, err = db.PrepareContext(ctx, updateToolCallInput); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateToolCallInput: %w", err)
	}
	if q.updateToolCallResultStmt, err = db.PrepareContext(ctx, updateToolCallResult); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateToolCallResult: %w", err)
	}
	if q.cancelToolCallStmt, err = db.PrepareContext(ctx, cancelToolCall); err != nil {
		return nil, fmt.Errorf("error preparing query CancelToolCall: %w", err)
	}
	if q.cancelSessionToolCallsStmt, err = db.PrepareContext(ctx, cancelSessionToolCalls); err != nil {
		return nil, fmt.Errorf("error preparing query CancelSessionToolCalls: %w", err)
	}
	if q.deleteToolCallStmt, err = db.PrepareContext(ctx, deleteToolCall); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteToolCall: %w", err)
	}
	if q.deleteSessionToolCallsStmt, err = db.PrepareContext(ctx, deleteSessionToolCalls); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionToolCalls: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createProjectStmt != nil {
		if cerr := q.createProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProjectStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteProjectStmt != nil {
		if cerr := q.deleteProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProjectStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionFilesStmt != nil {
		if cerr := q.deleteSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionFilesStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathAndSessionStmt != nil {
		if cerr := q.getFileByPathAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathAndSessionStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getProjectByIDStmt != nil {
		if cerr := q.getProjectByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectByIDStmt: %w", cerr)
		}
	}
	if q.getProjectSessionsStmt != nil {
		if cerr := q.getProjectSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectSessionsStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.listFilesByPathStmt != nil {
		if cerr := q.listFilesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesByPathStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listLatestSessionFilesStmt != nil {
		if cerr := q.listLatestSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionFilesStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listNewFilesStmt != nil {
		if cerr := q.listNewFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNewFilesStmt: %w", cerr)
		}
	}
	if q.listProjectsByUserStmt != nil {
		if cerr := q.listProjectsByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProjectsByUserStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateProjectStmt != nil {
		if cerr := q.updateProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProjectStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordStmt != nil {
		if cerr := q.updateUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordStmt: %w", cerr)
		}
	}
	if q.createToolCallStmt != nil {
		if cerr := q.createToolCallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createToolCallStmt: %w", cerr)
		}
	}
	if q.getToolCallStmt != nil {
		if cerr := q.getToolCallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getToolCallStmt: %w", cerr)
		}
	}
	if q.listToolCallsBySessionStmt != nil {
		if cerr := q.listToolCallsBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listToolCallsBySessionStmt: %w", cerr)
		}
	}
	if q.listToolCallsByMessageStmt != nil {
		if cerr := q.listToolCallsByMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listToolCallsByMessageStmt: %w", cerr)
		}
	}
	if q.listPendingToolCallsStmt != nil {
		if cerr := q.listPendingToolCallsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingToolCallsStmt: %w", cerr)
		}
	}
	if q.updateToolCallStatusStmt != nil {
		if cerr := q.updateToolCallStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateToolCallStatusStmt: %w", cerr)
		}
	}
	if q.updateToolCallInputStmt != nil {
		if cerr := q.updateToolCallInputStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateToolCallInputStmt: %w", cerr)
		}
	}
	if q.updateToolCallResultStmt != nil {
		if cerr := q.updateToolCallResultStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateToolCallResultStmt: %w", cerr)
		}
	}
	if q.cancelToolCallStmt != nil {
		if cerr := q.cancelToolCallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cancelToolCallStmt: %w", cerr)
		}
	}
	if q.cancelSessionToolCallsStmt != nil {
		if cerr := q.cancelSessionToolCallsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cancelSessionToolCallsStmt: %w", cerr)
		}
	}
	if q.deleteToolCallStmt != nil {
		if cerr := q.deleteToolCallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteToolCallStmt: %w", cerr)
		}
	}
	if q.deleteSessionToolCallsStmt != nil {
		if cerr := q.deleteSessionToolCallsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionToolCallsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                          DBTX
	tx                          *sql.Tx
	createFileStmt              *sql.Stmt
	createMessageStmt           *sql.Stmt
	createProjectStmt           *sql.Stmt
	createSessionStmt           *sql.Stmt
	createUserStmt              *sql.Stmt
	deleteFileStmt              *sql.Stmt
	deleteMessageStmt           *sql.Stmt
	deleteProjectStmt           *sql.Stmt
	deleteSessionStmt           *sql.Stmt
	deleteSessionFilesStmt      *sql.Stmt
	deleteSessionMessagesStmt   *sql.Stmt
	deleteUserStmt              *sql.Stmt
	getFileStmt                 *sql.Stmt
	getFileByPathAndSessionStmt *sql.Stmt
	getMessageStmt              *sql.Stmt
	getProjectByIDStmt          *sql.Stmt
	getProjectSessionsStmt      *sql.Stmt
	getSessionByIDStmt          *sql.Stmt
	getUserByEmailStmt          *sql.Stmt
	getUserByIDStmt             *sql.Stmt
	getUserByUsernameStmt       *sql.Stmt
	listFilesByPathStmt         *sql.Stmt
	listFilesBySessionStmt      *sql.Stmt
	listLatestSessionFilesStmt  *sql.Stmt
	listMessagesBySessionStmt   *sql.Stmt
	listNewFilesStmt            *sql.Stmt
	listProjectsByUserStmt      *sql.Stmt
	listSessionsStmt            *sql.Stmt
	updateMessageStmt           *sql.Stmt
	updateProjectStmt           *sql.Stmt
	updateSessionStmt           *sql.Stmt
	updateUserStmt              *sql.Stmt
	updateUserPasswordStmt      *sql.Stmt
	// Tool calls
	createToolCallStmt          *sql.Stmt
	getToolCallStmt             *sql.Stmt
	listToolCallsBySessionStmt  *sql.Stmt
	listToolCallsByMessageStmt  *sql.Stmt
	listPendingToolCallsStmt    *sql.Stmt
	updateToolCallStatusStmt    *sql.Stmt
	updateToolCallInputStmt     *sql.Stmt
	updateToolCallResultStmt    *sql.Stmt
	cancelToolCallStmt          *sql.Stmt
	cancelSessionToolCallsStmt  *sql.Stmt
	deleteToolCallStmt          *sql.Stmt
	deleteSessionToolCallsStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		tx:                          tx,
		createFileStmt:              q.createFileStmt,
		createMessageStmt:           q.createMessageStmt,
		createProjectStmt:           q.createProjectStmt,
		createSessionStmt:           q.createSessionStmt,
		createUserStmt:              q.createUserStmt,
		deleteFileStmt:              q.deleteFileStmt,
		deleteMessageStmt:           q.deleteMessageStmt,
		deleteProjectStmt:           q.deleteProjectStmt,
		deleteSessionStmt:           q.deleteSessionStmt,
		deleteSessionFilesStmt:      q.deleteSessionFilesStmt,
		deleteSessionMessagesStmt:   q.deleteSessionMessagesStmt,
		deleteUserStmt:              q.deleteUserStmt,
		getFileStmt:                 q.getFileStmt,
		getFileByPathAndSessionStmt: q.getFileByPathAndSessionStmt,
		getMessageStmt:              q.getMessageStmt,
		getProjectByIDStmt:          q.getProjectByIDStmt,
		getProjectSessionsStmt:      q.getProjectSessionsStmt,
		getSessionByIDStmt:          q.getSessionByIDStmt,
		getUserByEmailStmt:          q.getUserByEmailStmt,
		getUserByIDStmt:             q.getUserByIDStmt,
		getUserByUsernameStmt:       q.getUserByUsernameStmt,
		listFilesByPathStmt:         q.listFilesByPathStmt,
		listFilesBySessionStmt:      q.listFilesBySessionStmt,
		listLatestSessionFilesStmt:  q.listLatestSessionFilesStmt,
		listMessagesBySessionStmt:   q.listMessagesBySessionStmt,
		listNewFilesStmt:            q.listNewFilesStmt,
		listProjectsByUserStmt:      q.listProjectsByUserStmt,
		listSessionsStmt:            q.listSessionsStmt,
		updateMessageStmt:           q.updateMessageStmt,
		updateProjectStmt:           q.updateProjectStmt,
		updateSessionStmt:           q.updateSessionStmt,
		updateUserStmt:              q.updateUserStmt,
		updateUserPasswordStmt:      q.updateUserPasswordStmt,
		// Tool calls
		createToolCallStmt:          q.createToolCallStmt,
		getToolCallStmt:             q.getToolCallStmt,
		listToolCallsBySessionStmt:  q.listToolCallsBySessionStmt,
		listToolCallsByMessageStmt:  q.listToolCallsByMessageStmt,
		listPendingToolCallsStmt:    q.listPendingToolCallsStmt,
		updateToolCallStatusStmt:    q.updateToolCallStatusStmt,
		updateToolCallInputStmt:     q.updateToolCallInputStmt,
		updateToolCallResultStmt:    q.updateToolCallResultStmt,
		cancelToolCallStmt:          q.cancelToolCallStmt,
		cancelSessionToolCallsStmt:  q.cancelSessionToolCallsStmt,
		deleteToolCallStmt:          q.deleteToolCallStmt,
		deleteSessionToolCallsStmt:  q.deleteSessionToolCallsStmt,
	}
}
