// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql"
)

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Message struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	Role             string         `json:"role"`
	Parts            string         `json:"parts"`
	Model            sql.NullString `json:"model"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	FinishedAt       sql.NullInt64  `json:"finished_at"`
	Provider         sql.NullString `json:"provider"`
	IsSummaryMessage int64          `json:"is_summary_message"`
}

type Project struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	ExternalIP       string         `json:"external_ip"`
	FrontendPort     int32          `json:"frontend_port"`
	WorkspacePath    string         `json:"workspace_path"`
	ContainerName    sql.NullString `json:"container_name"`
	WorkdirPath      sql.NullString `json:"workdir_path"`
	DbHost           sql.NullString `json:"db_host"`
	DbPort           sql.NullInt32  `json:"db_port"`
	DbUser           sql.NullString `json:"db_user"`
	DbPassword       sql.NullString `json:"db_password"`
	DbName           sql.NullString `json:"db_name"`
	BackendPort      sql.NullInt32  `json:"backend_port"`
	FrontendCommand  sql.NullString `json:"frontend_command"`
	FrontendLanguage sql.NullString `json:"frontend_language"`
	BackendCommand   sql.NullString `json:"backend_command"`
	BackendLanguage  sql.NullString `json:"backend_language"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	ProjectID        sql.NullString `json:"project_id"`
}

type User struct {
	ID           string         `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}
