// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id,
    user_id,
    name,
    description,
    host,
    port,
    workspace_path,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    EXTRACT(EPOCH FROM NOW()) * 1000,
    EXTRACT(EPOCH FROM NOW()) * 1000
)
RETURNING id, user_id, name, description, host, port, workspace_path, created_at, updated_at
`

type CreateProjectParams struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	Host          string         `json:"host"`
	Port          int32          `json:"port"`
	WorkspacePath string         `json:"workspace_path"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.queryRow(ctx, q.createProjectStmt, createProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Host,
		arg.Port,
		arg.WorkspacePath,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Host,
		&i.Port,
		&i.WorkspacePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProjectStmt, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, user_id, name, description, host, port, workspace_path, created_at, updated_at
FROM projects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.queryRow(ctx, q.getProjectByIDStmt, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Host,
		&i.Port,
		&i.WorkspacePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectSessions = `-- name: GetProjectSessions :many
SELECT s.id, s.parent_session_id, s.title, s.message_count, s.prompt_tokens, s.completion_tokens, s.cost, s.updated_at, s.created_at, s.summary_message_id, s.project_id
FROM sessions s
WHERE s.project_id = $1
AND s.parent_session_id IS NULL
ORDER BY s.created_at DESC
`

func (q *Queries) GetProjectSessions(ctx context.Context, projectID sql.NullString) ([]Session, error) {
	rows, err := q.query(ctx, q.getProjectSessionsStmt, getProjectSessions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT id, user_id, name, description, host, port, workspace_path, created_at, updated_at
FROM projects
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListProjectsByUser(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.query(ctx, q.listProjectsByUserStmt, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Host,
			&i.Port,
			&i.WorkspacePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name = $2,
    description = $3,
    host = $4,
    port = $5,
    workspace_path = $6,
    updated_at = EXTRACT(EPOCH FROM NOW()) * 1000
WHERE id = $1
RETURNING id, user_id, name, description, host, port, workspace_path, created_at, updated_at
`

type UpdateProjectParams struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	Host          string         `json:"host"`
	Port          int32          `json:"port"`
	WorkspacePath string         `json:"workspace_path"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.queryRow(ctx, q.updateProjectStmt, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Host,
		arg.Port,
		arg.WorkspacePath,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Host,
		&i.Port,
		&i.WorkspacePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
