// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id,
    user_id,
    name,
    description,
    external_ip,
    frontend_port,
    workspace_path,
    container_name,
    workdir_path,
    db_host,
    db_port,
    db_user,
    db_password,
    db_name,
    backend_port,
    frontend_command,
    frontend_language,
    backend_command,
    backend_language,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
    EXTRACT(EPOCH FROM NOW()) * 1000,
    EXTRACT(EPOCH FROM NOW()) * 1000
)
RETURNING id, user_id, name, description, created_at, updated_at, external_ip, frontend_port, workspace_path, container_name, workdir_path, db_host, db_port, db_user, db_password, db_name, backend_port, frontend_command, frontend_language, backend_command, backend_language
`

type CreateProjectParams struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	ExternalIP       string         `json:"external_ip"`
	FrontendPort     int32          `json:"frontend_port"`
	WorkspacePath    string         `json:"workspace_path"`
	ContainerName    sql.NullString `json:"container_name"`
	WorkdirPath      sql.NullString `json:"workdir_path"`
	DbHost           sql.NullString `json:"db_host"`
	DbPort           sql.NullInt32  `json:"db_port"`
	DbUser           sql.NullString `json:"db_user"`
	DbPassword       sql.NullString `json:"db_password"`
	DbName           sql.NullString `json:"db_name"`
	BackendPort      sql.NullInt32  `json:"backend_port"`
	FrontendCommand  sql.NullString `json:"frontend_command"`
	FrontendLanguage sql.NullString `json:"frontend_language"`
	BackendCommand   sql.NullString `json:"backend_command"`
	BackendLanguage  sql.NullString `json:"backend_language"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.queryRow(ctx, q.createProjectStmt, createProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.ExternalIP,
		arg.FrontendPort,
		arg.WorkspacePath,
		arg.ContainerName,
		arg.WorkdirPath,
		arg.DbHost,
		arg.DbPort,
		arg.DbUser,
		arg.DbPassword,
		arg.DbName,
		arg.BackendPort,
		arg.FrontendCommand,
		arg.FrontendLanguage,
		arg.BackendCommand,
		arg.BackendLanguage,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalIP,
		&i.FrontendPort,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.WorkdirPath,
		&i.DbHost,
		&i.DbPort,
		&i.DbUser,
		&i.DbPassword,
		&i.DbName,
		&i.BackendPort,
		&i.FrontendCommand,
		&i.FrontendLanguage,
		&i.BackendCommand,
		&i.BackendLanguage,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProjectStmt, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, user_id, name, description, created_at, updated_at, external_ip, frontend_port, workspace_path, container_name, workdir_path, db_host, db_port, db_user, db_password, db_name, backend_port, frontend_command, frontend_language, backend_command, backend_language
FROM projects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.queryRow(ctx, q.getProjectByIDStmt, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalIP,
		&i.FrontendPort,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.WorkdirPath,
		&i.DbHost,
		&i.DbPort,
		&i.DbUser,
		&i.DbPassword,
		&i.DbName,
		&i.BackendPort,
		&i.FrontendCommand,
		&i.FrontendLanguage,
		&i.BackendCommand,
		&i.BackendLanguage,
	)
	return i, err
}

const getProjectSessions = `-- name: GetProjectSessions :many
SELECT s.id, s.parent_session_id, s.title, s.message_count, s.prompt_tokens, s.completion_tokens, s.cost, s.updated_at, s.created_at, s.summary_message_id, s.project_id
FROM sessions s
WHERE s.project_id = $1
AND s.parent_session_id IS NULL
ORDER BY s.created_at DESC
`

func (q *Queries) GetProjectSessions(ctx context.Context, projectID sql.NullString) ([]Session, error) {
	rows, err := q.query(ctx, q.getProjectSessionsStmt, getProjectSessions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT id, user_id, name, description, created_at, updated_at, external_ip, frontend_port, workspace_path, container_name, workdir_path, db_host, db_port, db_user, db_password, db_name, backend_port, frontend_command, frontend_language, backend_command, backend_language
FROM projects
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListProjectsByUser(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.query(ctx, q.listProjectsByUserStmt, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalIP,
			&i.FrontendPort,
			&i.WorkspacePath,
			&i.ContainerName,
			&i.WorkdirPath,
			&i.DbHost,
			&i.DbPort,
			&i.DbUser,
			&i.DbPassword,
			&i.DbName,
			&i.BackendPort,
			&i.FrontendCommand,
			&i.FrontendLanguage,
			&i.BackendCommand,
			&i.BackendLanguage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name = $2,
    description = $3,
    external_ip = $4,
    frontend_port = $5,
    workspace_path = $6,
    container_name = $7,
    workdir_path = $8,
    db_host = $9,
    db_port = $10,
    db_user = $11,
    db_password = $12,
    db_name = $13,
    backend_port = $14,
    frontend_command = $15,
    frontend_language = $16,
    backend_command = $17,
    backend_language = $18,
    updated_at = EXTRACT(EPOCH FROM NOW()) * 1000
WHERE id = $1
RETURNING id, user_id, name, description, created_at, updated_at, external_ip, frontend_port, workspace_path, container_name, workdir_path, db_host, db_port, db_user, db_password, db_name, backend_port, frontend_command, frontend_language, backend_command, backend_language
`

type UpdateProjectParams struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Description      sql.NullString `json:"description"`
	ExternalIP       string         `json:"external_ip"`
	FrontendPort     int32          `json:"frontend_port"`
	WorkspacePath    string         `json:"workspace_path"`
	ContainerName    sql.NullString `json:"container_name"`
	WorkdirPath      sql.NullString `json:"workdir_path"`
	DbHost           sql.NullString `json:"db_host"`
	DbPort           sql.NullInt32  `json:"db_port"`
	DbUser           sql.NullString `json:"db_user"`
	DbPassword       sql.NullString `json:"db_password"`
	DbName           sql.NullString `json:"db_name"`
	BackendPort      sql.NullInt32  `json:"backend_port"`
	FrontendCommand  sql.NullString `json:"frontend_command"`
	FrontendLanguage sql.NullString `json:"frontend_language"`
	BackendCommand   sql.NullString `json:"backend_command"`
	BackendLanguage  sql.NullString `json:"backend_language"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.queryRow(ctx, q.updateProjectStmt, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ExternalIP,
		arg.FrontendPort,
		arg.WorkspacePath,
		arg.ContainerName,
		arg.WorkdirPath,
		arg.DbHost,
		arg.DbPort,
		arg.DbUser,
		arg.DbPassword,
		arg.DbName,
		arg.BackendPort,
		arg.FrontendCommand,
		arg.FrontendLanguage,
		arg.BackendCommand,
		arg.BackendLanguage,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalIP,
		&i.FrontendPort,
		&i.WorkspacePath,
		&i.ContainerName,
		&i.WorkdirPath,
		&i.DbHost,
		&i.DbPort,
		&i.DbUser,
		&i.DbPassword,
		&i.DbName,
		&i.BackendPort,
		&i.FrontendCommand,
		&i.FrontendLanguage,
		&i.BackendCommand,
		&i.BackendLanguage,
	)
	return i, err
}
